# Generated by Django 3.0.4 on 2020-04-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverToPatients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgid', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('label', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'caregiver_to_patients',
                'managed': False,
            },
        ),
    ]
