# Generated by Django 3.0.4 on 2020-05-09 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_caregivertopatients'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patientsinfo',
            table='patients_new',
        ),
    ]
